# Generated by Django 4.2.3 on 2023-07-17 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creacion'],
            },
        ),
        migrations.CreateModel(
            name='Hilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizacion', models.DateTimeField(auto_now=True)),
                ('mensajes', models.ManyToManyField(to='Mensajes.mensaje')),
                ('usuarios', models.ManyToManyField(related_name='hilos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizacion'],
            },
        ),
    ]
